# Generated by Django 3.1.5 on 2021-01-31 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mainarticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainArticle',
        ),
    ]
