# Generated by Django 3.1.5 on 2021-01-31 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_mainarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.article')),
            ],
            bases=('main.article',),
        ),
    ]
